services:
  springboot-auction:
    container_name: springboot-auction
    image: springboot-auction:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-twitter:3306/auctiondb
      - SPRING_DATASOURCE_USERNAME=dev
      - SPRING_DATASOURCE_PASSWORD=dev123
    networks:
      - auction-network
    depends_on:
      - mysql-auction
  mysql-auction:
    container_name: mysql-auction
    image: mysql:9.3
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: auctiondb
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev123
    ports:
      - "3307:3306"
    networks:
      - auction-network
networks:
  auction-network:
    driver: bridge