version: '3.8'

services:
  nginx-auction:
    container_name: nginx-auction
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    networks:
      - auction-network
    depends_on:
      - springboot-auction
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    platform: linux/amd64
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  springboot-auction:
    container_name: springboot-auction
    image: gtaeu/springboot-auction:latest
    platform: linux/amd64
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-auction.cjgqoaggg3c5.ap-northeast-2.rds.amazonaws.com:3306/auctiondb
      - SPRING_DATASOURCE_USERNAME=dev
      - SPRING_DATASOURCE_PASSWORD=dev123
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}  # ← .env 파일에서
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
      - TOSS_SECRET_KEY=${TOSS_SECRET_KEY}
    networks:
      - auction-network


networks:
  auction-network:
    driver: bridge
