server {
    listen 80;
    server_name mmuuttssaa.shop www.mmuuttssaa.shop;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name mmuuttssaa.shop www.mmuuttssaa.shop;

    ssl_certificate /etc/letsencrypt/live/mmuuttssaa.shop/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/mmuuttssaa.shop/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers ECDHE-RSA-AES256-GCM-SHA512:DHE-RSA-AES256-GCM-SHA512:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384;


     location /api/notification/stream {
        proxy_pass http://springboot-auction:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        
        # SSE 설정
        proxy_http_version 1.1;
        proxy_set_header Connection '';
        proxy_buffering off;
        proxy_cache off;
        
        # 타임아웃 (1시간)
        proxy_read_timeout 3600s;
        proxy_connect_timeout 3600s;
        proxy_send_timeout 3600s;
        
        if ($request_method = 'OPTIONS') {
            return 204;
        }
    }

    location / {
        proxy_pass http://springboot-auction:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}