spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3307/auctiondb
    username: dev
    password: dev123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    org.hibernate.orm.jdbc.bind: trace

---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false