# ===============================
# default (local/test) 환경 → H2 사용
# ===============================
spring:
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MYSQL   # ✅ MySQL 호환 모드
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update   # create-drop 대신 update 추천
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB        # ✅ 파일 하나당 최대 10MB
      max-request-size: 50MB
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${OAUTH_KAKAO_CLIENT_ID}
            client-secret: ${OAUTH_KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket: ${AWS_S3_BUCKET}
    region:
      static: ap-northeast-2
    stack:
      auto: false


jwt:
  secret: my-secret-key-study-springboot-psbsbb
  access-token-expiration: 3600000    # 1시간
  refresh-token-expiration: 1209600000


---
# ===============================
# dev 환경 → MySQL 사용
# ===============================
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3307/auctiondb
    driver-class-name: com.mysql.cj.jdbc.Driver   # ✅ 여기서만 MySQL 드라이버 선언
    username: dev
    password: dev123
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB        # ✅ 파일 하나당 최대 10MB
      max-request-size: 50MB     # ✅ 전체 요청 최대 50MB
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${OAUTH_KAKAO_CLIENT_ID}
            client-secret: ${OAUTH_KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket: ${AWS_S3_BUCKET}
    region:
      static: ap-northeast-2
    stack:
      auto: false

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace

---
# ===============================
# prod 환경 → MySQL 사용
# ===============================
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect   # ✅ 이 줄 추가
    hibernate:
      ddl-auto: none
    show-sql: false
  servlet:
    multipart:
      max-file-size: 10MB        # ✅ 파일 하나당 최대 10MB
      max-request-size: 50MB     # ✅ 전체 요청 최대 50MB
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${OAUTH_KAKAO_CLIENT_ID}
            client-secret: ${OAUTH_KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket: ${AWS_S3_BUCKET}
    region:
      static: ap-northeast-2
    stack:
      auto: false